/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

    Principal framePrincipal = new Principal();
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new PanelGradient.PanelGradient();
        jLabel3 = new javax.swing.JLabel();
        materialButtomRectangle1 = new principal.MaterialButtomRectangle();
        panelGradient2 = new PanelGradient.PanelGradient();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jtfUser = new app.bolivia.swing.JCTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jbtCerrar = new javax.swing.JButton();
        jbtMinimizar = new javax.swing.JButton();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jpPass = new org.edisoncor.gui.passwordField.PasswordFieldRectBackground();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGradient1.setBackground(new java.awt.Color(255, 255, 255));
        panelGradient1.setideEndColor(new java.awt.Color(255, 255, 255));
        panelGradient1.setideStartColor(new java.awt.Color(80, 200, 208));
        panelGradient1.setideTransparentControls(false);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hello, Friend!");

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        getContentPane().add(panelGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 450));

        materialButtomRectangle1.setBackground(new java.awt.Color(80, 200, 208));
        materialButtomRectangle1.setBorder(null);
        materialButtomRectangle1.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle1.setText("LOGIN");
        materialButtomRectangle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialButtomRectangle1MouseClicked(evt);
            }
        });
        getContentPane().add(materialButtomRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 108, 42));

        panelGradient2.setBackground(new java.awt.Color(255, 255, 255));
        panelGradient2.setideEndColor(new java.awt.Color(255, 255, 255));
        panelGradient2.setideStartColor(new java.awt.Color(255, 255, 255));
        panelGradient2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        panelImage1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 43));

        jtfUser.setBorder(null);
        jtfUser.setForeground(new java.awt.Color(153, 153, 153));
        jtfUser.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jtfUser.setPlaceholder("USER NAME");
        panelImage1.add(jtfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 177, 20));
        panelImage1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 169, 9));

        panelGradient2.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 240, 51));

        jbtCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jbtCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jbtCerrar.setBorder(null);
        jbtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCerrarActionPerformed(evt);
            }
        });
        panelGradient2.add(jbtCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jbtMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        jbtMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize.png"))); // NOI18N
        jbtMinimizar.setBorder(null);
        jbtMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMinimizarActionPerformed(evt);
            }
        });
        panelGradient2.add(jbtMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        panelImage2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lock.png"))); // NOI18N
        panelImage2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 43));
        panelImage2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 169, 9));

        jpPass.setBorder(null);
        jpPass.setForeground(new java.awt.Color(153, 153, 153));
        jpPass.setColorDeBorde(new java.awt.Color(255, 255, 255));
        jpPass.setDescripcion(" contrseña");
        panelImage2.add(jpPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 160, 20));

        panelGradient2.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 240, 51));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(80, 200, 208));
        jLabel4.setText("Ingresa a MayLu");
        panelGradient2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 350, 60));

        getContentPane().add(panelGradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 460, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCerrarActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result =JOptionPane.showConfirmDialog(null, "Desea salir?", "Exit", dialog);
        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtCerrarActionPerformed

    private void jbtMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMinimizarActionPerformed
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jbtMinimizarActionPerformed

    private void materialButtomRectangle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialButtomRectangle1MouseClicked
        String a = jtfUser.getText();
        String b = jpPass.getText();
        String nom = "qiqe";
        String pas = "123";
        if(nom.equals(a) && pas.equals(b)){
            framePrincipal.setVisible(true);
            dispose();
        }else {
            JOptionPane.showMessageDialog(null, "contraseña incorrecta");
        }
    }//GEN-LAST:event_materialButtomRectangle1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtCerrar;
    private javax.swing.JButton jbtMinimizar;
    private org.edisoncor.gui.passwordField.PasswordFieldRectBackground jpPass;
    private app.bolivia.swing.JCTextField jtfUser;
    private principal.MaterialButtomRectangle materialButtomRectangle1;
    private PanelGradient.PanelGradient panelGradient1;
    private PanelGradient.PanelGradient panelGradient2;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    // End of variables declaration//GEN-END:variables
}
