/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

/**
 *
 * @author Usuario
 */
public class Pago extends javax.swing.JPanel {

    /**
     * Creates new form Pago
     */
    public Pago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        materialButtomRectangle1 = new principal.MaterialButtomRectangle();
        materialButtomRectangle2 = new principal.MaterialButtomRectangle();
        materialButtomRectangle3 = new principal.MaterialButtomRectangle();
        materialButtomRectangle4 = new principal.MaterialButtomRectangle();
        jLabel4 = new javax.swing.JLabel();
        materialButtomRectangle5 = new principal.MaterialButtomRectangle();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel1.setText("Total");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel2.setText("Efectivo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel3.setText("Cambio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jTextField1.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 76, 28));

        jTextField2.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 76, 30));

        materialButtomRectangle1.setBackground(new java.awt.Color(255, 51, 102));
        materialButtomRectangle1.setBorder(null);
        materialButtomRectangle1.setForeground(new java.awt.Color(153, 255, 255));
        materialButtomRectangle1.setText("$50.00");
        jPanel1.add(materialButtomRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 76, 36));

        materialButtomRectangle2.setBackground(new java.awt.Color(255, 51, 102));
        materialButtomRectangle2.setBorder(null);
        materialButtomRectangle2.setForeground(new java.awt.Color(153, 255, 255));
        materialButtomRectangle2.setText("$100.00");
        jPanel1.add(materialButtomRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 76, 36));

        materialButtomRectangle3.setBackground(new java.awt.Color(255, 51, 102));
        materialButtomRectangle3.setBorder(null);
        materialButtomRectangle3.setForeground(new java.awt.Color(153, 255, 255));
        materialButtomRectangle3.setText("$200.00");
        jPanel1.add(materialButtomRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 76, 36));

        materialButtomRectangle4.setBackground(new java.awt.Color(255, 51, 102));
        materialButtomRectangle4.setBorder(null);
        materialButtomRectangle4.setForeground(new java.awt.Color(153, 255, 255));
        materialButtomRectangle4.setText("$500.00");
        jPanel1.add(materialButtomRectangle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 76, 36));

        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel4.setText("$");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 76, 27));

        materialButtomRectangle5.setBackground(new java.awt.Color(255, 51, 102));
        materialButtomRectangle5.setBorder(null);
        materialButtomRectangle5.setForeground(new java.awt.Color(153, 255, 255));
        materialButtomRectangle5.setText("Realizar venta");
        jPanel1.add(materialButtomRectangle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 320, 133, 36));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 88, 102, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 100, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 420));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private principal.MaterialButtomRectangle materialButtomRectangle1;
    private principal.MaterialButtomRectangle materialButtomRectangle2;
    private principal.MaterialButtomRectangle materialButtomRectangle3;
    private principal.MaterialButtomRectangle materialButtomRectangle4;
    private principal.MaterialButtomRectangle materialButtomRectangle5;
    // End of variables declaration//GEN-END:variables
}
